export const LIST_STATUS_ACTION = {
  "SUCCESS": "SUCCESS",
  "LOADING": "LOADING",
  "FAILED": "FAILED",
  "EMPTY": "EMPTY"
};

export const URL_API = "http://localhost:4000";

export const GET_LIST_EMPLOYEE = "GET_LIST_EMPLOYEE";
export const GET_LIST_EMPLOYEE_RESPONSE = "GET_LIST_EMPLOYEE_RESPONSE";

export const GET_DETAIL_EMPLOYEE = "GET_DETAIL_EMPLOYEE";
export const GET_DETAIL_EMPLOYEE_RESPONSE = "GET_DETAIL_EMPLOYEE_RESPONSE";

export const CREATE_EMPLOYEE = "CREATE_EMPLOYEE";
export const CREATE_EMPLOYEE_RESPONSE = "CREATE_EMPLOYEE_RESPONSE";


export const EDIT_EMPLOYEE = "EDIT_EMPLOYEE";
export const EDIT_EMPLOYEE_RESPONSE = "EDIT_EMPLOYEE_RESPONSE";

export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE";
export const DELETE_EMPLOYEE_RESPONSE = "DELETE_EMPLOYEE_RESPONSE";